// Generated by CoffeeScript 1.6.3
var Alarm, DAVServer, Event, User, americano, caldavBackend, carddavBackend, cozy_Auth_Backend, cozy_CalBackend, cozy_CardBackend, cozy_PrincipalBackend, host, jsCalDAV_CalendarRoot, jsCardDAV_AddressBookRoot, jsDAV, jsDAVACL_PrincipalCollection, nodeCalDAV, nodeCardDAV, nodePrincipalCollection, port, principalBackend;

americano = require('americano');

jsDAV = require("cozy-jsdav-fork");

if (process.env.NODE_ENV !== 'test') {
  jsDAV.debugMode = true;
}

cozy_Auth_Backend = require('./server/backends/auth');

jsDAVACL_PrincipalCollection = require("cozy-jsdav-fork/lib/DAVACL/principalCollection");

cozy_PrincipalBackend = require('./server/backends/principal');

principalBackend = new cozy_PrincipalBackend;

nodePrincipalCollection = jsDAVACL_PrincipalCollection["new"](principalBackend);

jsCardDAV_AddressBookRoot = require("cozy-jsdav-fork/lib/CardDAV/addressBookRoot");

cozy_CardBackend = require('./server/backends/carddav');

carddavBackend = new cozy_CardBackend(require('./server/models/contact'));

nodeCardDAV = jsCardDAV_AddressBookRoot["new"](principalBackend, carddavBackend);

Event = require('./server/models/event');

Alarm = require('./server/models/alarm');

User = require('./server/models/user');

jsCalDAV_CalendarRoot = require("cozy-jsdav-fork/lib/CalDAV/calendarRoot");

cozy_CalBackend = require('./server/backends/caldav');

caldavBackend = new cozy_CalBackend(Event, Alarm, User);

nodeCalDAV = jsCalDAV_CalendarRoot["new"](principalBackend, caldavBackend);

DAVServer = jsDAV.mount({
  server: true,
  standalone: false,
  realm: 'jsDAV',
  mount: '/public/webdav/',
  authBackend: cozy_Auth_Backend["new"](),
  plugins: [require("cozy-jsdav-fork/lib/DAV/plugins/auth"), require("cozy-jsdav-fork/lib/CardDAV/plugin"), require("cozy-jsdav-fork/lib/CalDAV/plugin"), require("cozy-jsdav-fork/lib/DAVACL/plugin")],
  node: [nodePrincipalCollection, nodeCardDAV, nodeCalDAV]
});

port = process.env.PORT || 9116;

host = process.env.HOST || "127.0.0.1";

americano.start({
  name: 'webdav',
  port: port
}, function(app) {
  app.use('/public', function(req, res) {
    req.url = "/public/webdav" + req.url;
    return DavServer.exec(req, res);
  });
  return console.log("WebDAV Server listening on %s:%d within %s environment", host, port, app.get('env'));
});
