// Generated by CoffeeScript 1.6.3
var account;

account = require('./account');

module.exports = {
  '': {
    get: account.index
  },
  'token': {
    get: account.getCredentials,
    post: account.createCredentials
  }
};
